### PR TITLE
Removal of GetDecision and DeliberateVote methods

### PR DESCRIPTION
**Pull request by daracos**
Issue 1: Infrastructure team is going to expect a particular type returned for each vote e.g. map[uuid.UUID]bool for voting to accept agent. Currently our functions return interfaces which will have to be asserted with the type infrastructure is expecting.
Solution: For each voting function let's just return the type that infrastructure is expecting and rather than an interface type Removes need for asserting the type later in the code. 

Issue 2: Go is statically typed, so our GetDecision() and DeliberateVote() methods can only return a certain type. But, each vote will require us to return a different type e.g. map[uuid.UUID]bool or map[uuid.UUID]float64. My understanding is that both of these methods simply call the correct vote function. 
Solution: Let's just remove the GetDecision() and DeliberateVote() methods and place the voting function directly in the baseBiker method when we override it e.g. in DecideJoining() we calle VoteToAcceptWrapper

Issue 3: For voteInputs, each vote type may have a different type of Candidate e.g. list of agent UUIDs or list of governance types reperesented as ints.
Solution: Make a CandidateType struct consisting of all of the possible candidate types. Then, only input the relevant candidate type fromm the CandidateType struct into our voting function e.g. VoteToAcceptWrapper will only be provided with Candidates.AgentCandidate which is a list of agent UUIDs.

Happy to have a meeting to discuss and explain further.

### CODE REVIEW

**Review by btarifi10 — COMMENTED** [review]
Hey Dara,

I think this approach does work. I had some discussions with Ally too about another approach where we would simplify the voting framework substantially, and instantiate a new one for each vote. For example we could have an IdVoteHandler which inherits the base interface and returns the IdVoteMap type. This way we wouldn't need to do `deliberateVote` with the enum and the agent wouldn't have a single Voting framework but instead would do something like

```
func (*biker) DecideJoining() map[uuid.UUID]bool {

inputs := ...
voteOnJoiningHandler := NewVoteOnJoinHandler(inputs)

return voteOnJoiningHandler.GetDecision()
}
```

Let me know your thoughts on this approach - I'm not too set on either way.

**Comment by daracos** [comment]
Hey Basheq, cool, your idea sounds better as its more consistent with the other frameworks such as NavigationDecisionFramework. Just so I'm clear, would the code then look something like below? Where would the IdVoteHandler come into it? Or is the VoteOnJoinHandler the IdVoteHandler in this case? Please correct me if I'm wrong anywhere! :)

```go
type VoteOnJoinHandler struct {
   IDecisionFramework[IdVoteInputs, IdVoteMap]
  *inputs IdVoteInputs
}

func (*vojh VoteOnJoinHandler) GetDecision(IdVoteInputs) IdVoteMap {
   // call our current VoteToAcceptWrapper function
   return vote
}

func NewVoteOnJoinHandler() *VoteOnJoinHandler {
   return &VoteOnJoinHandler{
      inputs: &IdVoteInputs{},
   }
}
```

**Comment by btarifi10** [comment]
Yeah that looks exactly like what I had in mind!

**Comment by daracos** [comment]
Discussion continued offline. Merging the current proposal for now as it can then be easily adapted to Basheq's approach.

**Pull request merged**
